// Code generated by "stringer -type=Page"; DO NOT EDIT

package pages

import "fmt"

const _Page_name = "InputsOutputsFilingSnapshotsPatchbayPluginsOptions"

var _Page_index = [...]uint8{0, 6, 13, 19, 28, 36, 43, 50}

func (i Page) String() string {
	if i < 0 || i >= Page(len(_Page_index)-1) {
		return fmt.Sprintf("Page(%d)", i)
	}
	return _Page_name[_Page_index[i]:_Page_index[i+1]]
}
