// Code generated by "stringer -type Action"; DO NOT EDIT

package actions

import "fmt"

const _Action_name = "UnknownNoopPingSelectInputInputBankInputGainSelectOutputSetOutputLevel"

var _Action_index = [...]uint8{0, 7, 11, 15, 26, 35, 44, 56, 70}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return fmt.Sprintf("Action(%d)", i)
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
