// generated by stringer -type=Action; DO NOT EDIT

package actions

import "fmt"

const _Action_name = "UnknownPingDropPacketSelectInputInputBankInputGainSelectOutputOutputLevel"

var _Action_index = [...]uint8{0, 7, 11, 21, 32, 41, 50, 62, 73}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return fmt.Sprintf("Action(%d)", i)
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
