// Code generated by "stringer -type=Meter"; DO NOT EDIT

package meters

import "fmt"

const _Meter_name = "SmallVerticalMediumHorizontalLargeVertical"

var _Meter_index = [...]uint8{0, 13, 29, 42}

func (i Meter) String() string {
	if i < 0 || i >= Meter(len(_Meter_index)-1) {
		return fmt.Sprintf("Meter(%d)", i)
	}
	return _Meter_name[_Meter_index[i]:_Meter_index[i+1]]
}
