run:
  timeout: 5m
  allow-parallel-runners: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - gosimple
    - unused
    - typecheck
    - gofmt
    - goimports
    - misspell
    - revive
    - unparam
    - prealloc
    - stylecheck
  disable:
    # Often noisy for legacy codebases; re-enable later if desired
    - dupl
    - gochecknoinits
    - gochecknoglobals

linters-settings:
  goimports:
    local-prefixes: github.com/kward/venue
  gocyclo:
    min-complexity: 15
  revive:
    # Start with a minimal, less chatty rule set
    severity: warning
    rules:
      - name: empty-block
      - name: exported
      - name: if-return
      - name: import-shadowing
      - name: indent-error-flow
        disabled: true
      - name: receiver-naming

issues:
  exclude-use-default: false
  exclude-rules:
    # Keep tests pragmatic; reduce noise from complexity/dup/style in tests
    - path: _test\.go$
      linters:
        - gocyclo
        - dupl
        - stylecheck
    # Ignore generated and vendor code
    - path: ^vendor/
      linters:
        - "*"

output:
  formats:
    - format: colored-line-number
