language: go

os:
  - linux
  - osx

go:
  - 1.3
  - tip

install:
  # github.com/howeyc/gopass requires Go v1.3.
  - go get github.com/howeyc/gopass
  - go get github.com/kward/go-osc/osc
  - go get github.com/kward/go-vnc
  - go get golang.org/x/net/context
