language: go

os:
  - linux
  - osx

go:
  # Go 1.13 required for testing.Init() support.
  - 1.13
  - tip

install:
  # github.com/howeyc/gopass requires Go 1.3.
  - go get github.com/howeyc/gopass

  # github.com/kward/go-osc/osc requires Go 1.2.
  - go get github.com/kward/go-osc/osc
  - go get golang.org/x/net/context

  # github.com/kward/go-vnc requires Go 1.2.
  - go get github.com/kward/go-vnc

  - go get github.com/golang/glog
