// Code generated by "stringer -type Control"; DO NOT EDIT

package controls

import "fmt"

const _Control_name = "UnknownSelectGainSoloSoloClear"

var _Control_index = [...]uint8{0, 7, 13, 17, 21, 30}

func (i Control) String() string {
	if i < 0 || i >= Control(len(_Control_index)-1) {
		return fmt.Sprintf("Control(%d)", i)
	}
	return _Control_name[_Control_index[i]:_Control_index[i+1]]
}
