// Code generated by "stringer -type=Control"; DO NOT EDIT

package controls

import "fmt"

const _Control_name = "UnknownSelectAuxAuxPanDelayFaderGainGroupGroupPanHPFPanSoloSoloClearVarGroups"

var _Control_index = [...]uint8{0, 7, 13, 16, 22, 27, 32, 36, 41, 49, 52, 55, 59, 68, 77}

func (i Control) String() string {
	if i < 0 || i >= Control(len(_Control_index)-1) {
		return fmt.Sprintf("Control(%d)", i)
	}
	return _Control_name[_Control_index[i]:_Control_index[i+1]]
}
