// Code generated by "stringer -type=Message"; DO NOT EDIT

package messages

import "fmt"

const _Message_name = "UnknownSetPixelFormatSetEncodingsFramebufferUpdateRequestKeyEventPointerEventClientCutTextFramebufferUpdateSetColorMapEntriesBellServerCutTextSleep"

var _Message_index = [...]uint8{0, 7, 21, 33, 57, 65, 77, 90, 107, 125, 129, 142, 147}

func (i Message) String() string {
	if i < 0 || i >= Message(len(_Message_index)-1) {
		return fmt.Sprintf("Message(%d)", i)
	}
	return _Message_name[_Message_index[i]:_Message_index[i+1]]
}
