// Code generated by "stringer -type=Signal"; DO NOT EDIT

package signals

import "fmt"

const _Signal_name = "UnknownInputFXReturnDirectInsertAuxGroupVarGroupMatrixMains"

var _Signal_index = [...]uint8{0, 7, 12, 20, 26, 32, 35, 40, 48, 54, 59}

func (i Signal) String() string {
	if i < 0 || i >= Signal(len(_Signal_index)-1) {
		return fmt.Sprintf("Signal(%d)", i)
	}
	return _Signal_name[_Signal_index[i]:_Signal_index[i+1]]
}
