// Generate proto code by running the following from the parent directory:
// $ protoc --go_out=. proto/*.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: proto/dshow_input_channel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DShowInputChannel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Storage     *DShowInputChannel_Storage     `protobuf:"bytes,1,opt,name=storage,proto3,oneof" json:"storage,omitempty"`
	Version     *DShowInputChannel_Version     `protobuf:"bytes,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
	UserComment *DShowInputChannel_UserComment `protobuf:"bytes,5,opt,name=userComment,proto3,oneof" json:"userComment,omitempty"`
	Strip       *DShowInputChannel_Strip       `protobuf:"bytes,14,opt,name=strip,proto3,oneof" json:"strip,omitempty"`
}

func (x *DShowInputChannel) Reset() {
	*x = DShowInputChannel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dshow_input_channel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DShowInputChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DShowInputChannel) ProtoMessage() {}

func (x *DShowInputChannel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dshow_input_channel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DShowInputChannel.ProtoReflect.Descriptor instead.
func (*DShowInputChannel) Descriptor() ([]byte, []int) {
	return file_proto_dshow_input_channel_proto_rawDescGZIP(), []int{0}
}

func (x *DShowInputChannel) GetStorage() *DShowInputChannel_Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *DShowInputChannel) GetVersion() *DShowInputChannel_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *DShowInputChannel) GetUserComment() *DShowInputChannel_UserComment {
	if x != nil {
		return x.UserComment
	}
	return nil
}

func (x *DShowInputChannel) GetStrip() *DShowInputChannel_Strip {
	if x != nil {
		return x.Strip
	}
	return nil
}

type DShowInputChannel_Storage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Offset int32  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DShowInputChannel_Storage) Reset() {
	*x = DShowInputChannel_Storage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dshow_input_channel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DShowInputChannel_Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DShowInputChannel_Storage) ProtoMessage() {}

func (x *DShowInputChannel_Storage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dshow_input_channel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DShowInputChannel_Storage.ProtoReflect.Descriptor instead.
func (*DShowInputChannel_Storage) Descriptor() ([]byte, []int) {
	return file_proto_dshow_input_channel_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DShowInputChannel_Storage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DShowInputChannel_Storage) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DShowInputChannel_Storage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DShowInputChannel_Version struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Offset  int32  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Version uint32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *DShowInputChannel_Version) Reset() {
	*x = DShowInputChannel_Version{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dshow_input_channel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DShowInputChannel_Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DShowInputChannel_Version) ProtoMessage() {}

func (x *DShowInputChannel_Version) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dshow_input_channel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DShowInputChannel_Version.ProtoReflect.Descriptor instead.
func (*DShowInputChannel_Version) Descriptor() ([]byte, []int) {
	return file_proto_dshow_input_channel_proto_rawDescGZIP(), []int{0, 1}
}

func (x *DShowInputChannel_Version) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DShowInputChannel_Version) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DShowInputChannel_Version) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DShowInputChannel_UserComment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Offset int32  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DShowInputChannel_UserComment) Reset() {
	*x = DShowInputChannel_UserComment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dshow_input_channel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DShowInputChannel_UserComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DShowInputChannel_UserComment) ProtoMessage() {}

func (x *DShowInputChannel_UserComment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dshow_input_channel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DShowInputChannel_UserComment.ProtoReflect.Descriptor instead.
func (*DShowInputChannel_UserComment) Descriptor() ([]byte, []int) {
	return file_proto_dshow_input_channel_proto_rawDescGZIP(), []int{0, 2}
}

func (x *DShowInputChannel_UserComment) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DShowInputChannel_UserComment) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DShowInputChannel_UserComment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DShowInputChannel_Strip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Offset int32  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DShowInputChannel_Strip) Reset() {
	*x = DShowInputChannel_Strip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dshow_input_channel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DShowInputChannel_Strip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DShowInputChannel_Strip) ProtoMessage() {}

func (x *DShowInputChannel_Strip) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dshow_input_channel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DShowInputChannel_Strip.ProtoReflect.Descriptor instead.
func (*DShowInputChannel_Strip) Descriptor() ([]byte, []int) {
	return file_proto_dshow_input_channel_proto_rawDescGZIP(), []int{0, 3}
}

func (x *DShowInputChannel_Strip) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DShowInputChannel_Strip) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DShowInputChannel_Strip) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_dshow_input_channel_proto protoreflect.FileDescriptor

var file_proto_dshow_input_channel_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x05, 0x0a, 0x11, 0x44, 0x53, 0x68,
	0x6f, 0x77, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x3f,
	0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x53, 0x68, 0x6f, 0x77, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x3f, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x53, 0x68, 0x6f, 0x77, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x48, 0x01, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01,
	0x12, 0x4b, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x53,
	0x68, 0x6f, 0x77, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x02, 0x52, 0x0b, 0x75,
	0x73, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x39, 0x0a,
	0x05, 0x73, 0x74, 0x72, 0x69, 0x70, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x53, 0x68, 0x6f, 0x77, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x70, 0x48, 0x03, 0x52, 0x05,
	0x73, 0x74, 0x72, 0x69, 0x70, 0x88, 0x01, 0x01, 0x1a, 0x4b, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x51, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x4f, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x49, 0x0a, 0x05, 0x53, 0x74, 0x72,
	0x69, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x0e, 0x0a, 0x0c,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x73, 0x74, 0x72, 0x69, 0x70, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dshow_input_channel_proto_rawDescOnce sync.Once
	file_proto_dshow_input_channel_proto_rawDescData = file_proto_dshow_input_channel_proto_rawDesc
)

func file_proto_dshow_input_channel_proto_rawDescGZIP() []byte {
	file_proto_dshow_input_channel_proto_rawDescOnce.Do(func() {
		file_proto_dshow_input_channel_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dshow_input_channel_proto_rawDescData)
	})
	return file_proto_dshow_input_channel_proto_rawDescData
}

var file_proto_dshow_input_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_dshow_input_channel_proto_goTypes = []interface{}{
	(*DShowInputChannel)(nil),             // 0: proto.DShowInputChannel
	(*DShowInputChannel_Storage)(nil),     // 1: proto.DShowInputChannel.Storage
	(*DShowInputChannel_Version)(nil),     // 2: proto.DShowInputChannel.Version
	(*DShowInputChannel_UserComment)(nil), // 3: proto.DShowInputChannel.UserComment
	(*DShowInputChannel_Strip)(nil),       // 4: proto.DShowInputChannel.Strip
}
var file_proto_dshow_input_channel_proto_depIdxs = []int32{
	1, // 0: proto.DShowInputChannel.storage:type_name -> proto.DShowInputChannel.Storage
	2, // 1: proto.DShowInputChannel.version:type_name -> proto.DShowInputChannel.Version
	3, // 2: proto.DShowInputChannel.userComment:type_name -> proto.DShowInputChannel.UserComment
	4, // 3: proto.DShowInputChannel.strip:type_name -> proto.DShowInputChannel.Strip
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_dshow_input_channel_proto_init() }
func file_proto_dshow_input_channel_proto_init() {
	if File_proto_dshow_input_channel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dshow_input_channel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DShowInputChannel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dshow_input_channel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DShowInputChannel_Storage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dshow_input_channel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DShowInputChannel_Version); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dshow_input_channel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DShowInputChannel_UserComment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dshow_input_channel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DShowInputChannel_Strip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_dshow_input_channel_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dshow_input_channel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dshow_input_channel_proto_goTypes,
		DependencyIndexes: file_proto_dshow_input_channel_proto_depIdxs,
		MessageInfos:      file_proto_dshow_input_channel_proto_msgTypes,
	}.Build()
	File_proto_dshow_input_channel_proto = out.File
	file_proto_dshow_input_channel_proto_rawDesc = nil
	file_proto_dshow_input_channel_proto_goTypes = nil
	file_proto_dshow_input_channel_proto_depIdxs = nil
}
