// Code generated by "stringer -type=Encoder"; DO NOT EDIT

package encoders

import "fmt"

const _Encoder_name = "TopLeftTopRightMiddleLeftMiddleRightBottomLeftBottomCenterBottomRight"

var _Encoder_index = [...]uint8{0, 7, 15, 25, 36, 46, 58, 69}

func (i Encoder) String() string {
	if i < 0 || i >= Encoder(len(_Encoder_index)-1) {
		return fmt.Sprintf("Encoder(%d)", i)
	}
	return _Encoder_name[_Encoder_index[i]:_Encoder_index[i+1]]
}
