// Code generated by "stringer -type=Size"; DO NOT EDIT

package switches

import "fmt"

const _Size_name = "TinySmallMediumLarge"

var _Size_index = [...]uint8{0, 4, 9, 15, 20}

func (i Size) String() string {
	if i < 0 || i >= Size(len(_Size_index)-1) {
		return fmt.Sprintf("Size(%d)", i)
	}
	return _Size_name[_Size_index[i]:_Size_index[i+1]]
}
