// Code generated by "stringer -type=Command commands.go"; DO NOT EDIT

package commands

import "fmt"

const _Command_name = "UnknownPingInputInputBankInputGainOutputOutputLevel"

var _Command_index = [...]uint8{0, 7, 11, 16, 25, 34, 40, 51}

func (i Command) String() string {
	if i < 0 || i >= Command(len(_Command_index)-1) {
		return fmt.Sprintf("Command(%d)", i)
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
